# These are supported funding model platforms

github: Running low on Resources if your viewing my otherwork or see this message im working local and not on web
buy_me_a_coffee: Paypal @mlomez88
custom: Paypal @mlomez88
